CREATE DATABASE UNOESC_BANK;

USE UNOESC_BANK;

CREATE TABLE CLIENTS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255)
);

CREATE TABLE ACCOUNTS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUM VARCHAR(10) NOT NULL,
    CLIENT_ID INT NOT NULL,
	CONSTRAINT FK_CLIENT_ID_ACCOUNT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);

CREATE TABLE TRANSACTIONS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL,
    TRANSACTION_TYPE INT NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    VALUE FLOAT NOT NULL
);

-- DEFININDO UMA FK POSTERIORMENTE A CRIACAO DA TABELA
ALTER TABLE TRANSACTIONS
ADD FOREIGN KEY (ACCOUNT_ID)
REFERENCES ACCOUNTS (ID);

-- CRIANDO INDICES
CREATE INDEX IDX_TRANSACTION_TP_TRANSACTION
ON TRANSACTIONS (TRANSACTION_TYPE);

CREATE INDEX IDX_TRANSACTION_DATE_TIME
ON TRANSACTIONS (DATE_TIME);